---
apiVersion: v2
name: odoo
description: An opiniated Helm Chart for deploying Odoo
type: application
version: 0.2.5
appVersion: "16.0"
sources:
  - https://github.com/odoo/odoo
  - https://github.com/imio/helm-charts
  - https://github.com/imio/helm-odoo
icon: https://odoocdn.com/openerp_website/static/src/img/assets/png/odoo_logo_medium.png
maintainers:
  - name: IMIO
    url: https://github.com/IMIO/
dependencies:
  - name: postgresql
    alias: postgresql
    version: 12.8.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
